import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="w-full h-screen bg-teal-50 flex justify-center items-center">
        <h1>Hello King!</h1>
      </main>

      <footer></footer>
    </div>
  );
}
